const assert = require('node:assert/strict')
const fs = require('node:fs')
const test = require('node:test')
const ts = require('typescript')
require.extensions['.ts'] = (module, filename) => {
  module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 }
  }).outputText, filename)
}
const { useStore } = require('../src/renderer/src/engine/store.ts')
const { useSecurity } = require('../src/renderer/src/engine/security.ts')
const { findDst } = require('../src/renderer/src/engine/traditionalIo.ts')
const { parseDevice, savedDeviceKey } = require('../src/renderer/src/engine/deviceLifecycle.ts')
function fixture(run) {
  const before = { store: useStore.getState(), security: useSecurity.getState(), window: global.window }
  const alerts = [], database = new Map()
  global.window = { alert: message => alerts.push(message), localStorage: {
    setItem: (k, v) => database.set(k, v), getItem: k => database.get(k) ?? null
  } }
  try {
    useSecurity.setState({ currentUser: 'admin', locked: false })
    const s = useStore.getState()
    s.newProject('blank')
    useStore.setState({ running: true })
    for (const [tag, type] of [['MTR', 'MOTOR'], ['XV', 'VALVE'], ['OTHER', 'MOTOR']]) {
      assert.equal(s.createModule({ tag, type, area: 'FEED', description: 'Saved device test' }), true)
    }
    for (const tag of ['CTLR', 'CTLR2']) {
      s.createController(tag, 'Saved device controller')
      s.commissionController(tag)
      for (const [slot, type, dst] of [[3, 'DI', `${tag}-IN`], [4, 'DO', `${tag}-OUT`]]) {
        assert.equal(s.addTraditionalCard(tag, slot, type), true)
        assert.equal(s.configureTraditionalChannel(`${tag}/C0${slot}`, 2, { dst, enabled: true }), true)
      }
    }
    s.tick(.1)
    run(s, alerts, database)
  } finally {
    useStore.setState(before.store, true)
    useSecurity.setState(before.security, true)
    if (before.window === undefined) delete global.window
    else global.window = before.window
  }
}
function m(tag = 'MTR') { return useStore.getState().modules[tag] }
function record(tag = 'MTR') { return useStore.getState().deviceLifecycle[tag] }
function prepare(s, tag = 'MTR', controller = 'CTLR') {
  assert.equal(s.enableDeviceLifecycle(tag), true)
  assert.equal(s.editDeviceDraft(tag, { controllerTag: controller, inputDst: `${controller}-IN`, outputDst: `${controller}-OUT` }), true)
  assert.equal(s.saveDeviceConfiguration(tag), true)
}
test('opt-in saved device inhibits Start and stale commands before first download; unmanaged modules retain behavior', () => fixture((s, alerts) => {
  assert.equal(s.enableDeviceLifecycle('MTR'), true)
  s.startMotor('MTR')
  assert.equal(m().commanded, false)
  assert.match(alerts.at(-1), /download/i)
  useStore.setState(state => ({ modules: { ...state.modules, MTR: { ...m(), commanded: true } } }))
  for (let i = 0; i < 30; i++) s.tick(.1)
  assert.equal(m().running, false)
  assert.equal(m().outputCommand, false)
  assert.equal(m().ioInputBad, true)
  s.startMotor('OTHER')
  for (let i = 0; i < 30; i++) s.tick(.1)
  assert.equal(m('OTHER').running, true)
}))
test('offline options/DST/source edits and Save leave live configuration and bindings unchanged', () => fixture((s, _, database) => {
  prepare(s)
  s.setDeviceOptions('MTR', { resetRequired: false, permissiveRequired: true })
  s.setPermissiveSource('MTR', 'OTHER')
  assert.equal(s.bindDeviceDst('MTR', 'input', 'ctlr2-in'), true)
  assert.equal(record().draft.inputDst, 'CTLR2-IN')
  assert.equal(record().draft.permissiveRequired, true)
  assert.equal(m().permissiveRequired, false)
  assert.equal(m().permissiveSource, undefined)
  assert.equal(useStore.getState().hardware.deviceBindings?.MTR, undefined)
  assert.equal(s.saveDeviceConfiguration('MTR'), true)
  assert.equal(parseDevice(database.get(savedDeviceKey('MTR')), 'MTR').permissiveRequired, true)
  assert.equal(m().downloaded, false)
}))
test('Full device download applies only saved fields; actual independent DI confirmation controls feedback', () => fixture(s => {
  prepare(s)
  assert.equal(s.downloadDeviceConfiguration('MTR'), true)
  assert.equal(record().online, true)
  assert.equal(m().downloaded, true)
  assert.equal(m().controllerTag, 'CTLR')
  assert.equal(m().appliedCommand ?? false, false)
  assert.equal(record().deployedRevision, record().savedRevision)
  s.tick(.1)
  s.startMotor('MTR')
  for (let i = 0; i < 30; i++) s.tick(.1)
  assert.equal(findDst(useStore.getState().hardware, 'CTLR-OUT').channel.value, 1)
  assert.equal(m().running, false)
  assert.equal(s.setTraditionalInput('CTLR-IN', 1), true)
  s.tick(.1)
  assert.equal(m().running, true)
  assert.equal(m().dcState, 'CONFIRMED_ACTIVE')
}))
test('an existing passive live binding can enter saved lifecycle without poisoning healthy physical channel quality', () => fixture(s => {
  assert.equal(s.bindDeviceDst('MTR', 'input', 'CTLR-IN'), true)
  assert.equal(s.bindDeviceDst('MTR', 'output', 'CTLR-OUT'), true)
  s.tick(.1)
  assert.equal(s.enableDeviceLifecycle('MTR'), true)
  s.tick(.1)
  assert.equal(m().ioInputBad, true)
  assert.equal(m().ioOutputBad, true)
  assert.equal(findDst(useStore.getState().hardware, 'CTLR-OUT').channel.bad, false)
  assert.equal(record().draft.controllerTag, 'CTLR')
  s.saveDeviceConfiguration('MTR')
  assert.equal(s.downloadDeviceConfiguration('MTR'), true)
  s.tick(.1)
  assert.equal(m().ioOutputBad, false)
}))
test('saved VALVE follows same deployment and does not infer open from successful output', () => fixture(s => {
  prepare(s, 'XV')
  assert.equal(s.downloadDeviceConfiguration('XV'), true)
  s.tick(.1)
  s.openValve('XV')
  s.tick(.1)
  assert.equal(m('XV').open, false)
  assert.equal(findDst(useStore.getState().hardware, 'CTLR-OUT').channel.value, 1)
  s.setTraditionalInput('CTLR-IN', 1)
  s.tick(.1)
  assert.equal(m('XV').open, true)
}))
test('unsaved edits, unavailable controller, mixed ownership, Bad channels and duplicate writers reject atomically', () => fixture(s => {
  prepare(s)
  s.editDeviceDraft('MTR', { confirmTimeSec: 3 })
  assert.equal(s.downloadDeviceConfiguration('MTR'), false)
  s.saveDeviceConfiguration('MTR')
  s.editDeviceDraft('MTR', { inputDst: 'CTLR2-IN' })
  s.saveDeviceConfiguration('MTR')
  assert.equal(s.downloadDeviceConfiguration('MTR'), false)
  s.editDeviceDraft('MTR', { inputDst: 'CTLR-IN' })
  s.saveDeviceConfiguration('MTR')
  s.configureTraditionalChannel('CTLR/C03', 2, { dst: 'CTLR-IN', enabled: false })
  assert.equal(s.downloadDeviceConfiguration('MTR'), false)
  s.configureTraditionalChannel('CTLR/C03', 2, { dst: 'CTLR-IN', enabled: true })
  s.tick(.1)
  assert.equal(s.bindDeviceDst('OTHER', 'output', 'CTLR-OUT'), true)
  assert.equal(s.downloadDeviceConfiguration('MTR'), false)
  s.bindDeviceDst('OTHER', 'output', '')
  s.failController('CTLR')
  assert.equal(s.downloadDeviceConfiguration('MTR'), false)
  assert.equal(record().deployed, undefined)
  assert.equal(m().downloaded, false)
  assert.equal(useStore.getState().hardware.deviceBindings.MTR, undefined)
}))
test('online edits reject; failed later download retains previous deployed runtime/bindings/revision', () => fixture(s => {
  prepare(s)
  assert.equal(s.downloadDeviceConfiguration('MTR'), true)
  const revision = record().deployedRevision
  assert.equal(s.editDeviceDraft('MTR', { confirmTimeSec: 7 }), false)
  s.setDeviceOnline('MTR', false)
  assert.equal(s.editDeviceDraft('MTR', { confirmTimeSec: 7, outputDst: 'MISSING' }), true)
  s.saveDeviceConfiguration('MTR')
  const before = JSON.stringify({ module: m(), binding: useStore.getState().hardware.deviceBindings.MTR, deployed: record().deployed })
  assert.equal(s.downloadDeviceConfiguration('MTR'), false)
  assert.equal(JSON.stringify({ module: m(), binding: useStore.getState().hardware.deviceBindings.MTR, deployed: record().deployed }), before)
  assert.equal(record().deployedRevision, revision)
}))
test('persistent load restores only offline draft across new project; corrupt/type-conflicting data rejects without mutation', () => fixture((s, _, db) => {
  prepare(s)
  s.editDeviceDraft('MTR', { confirmTimeSec: 6 })
  s.saveDeviceConfiguration('MTR')
  const saved = db.get(savedDeviceKey('MTR'))
  s.newProject('blank')
  s.createModule({ tag: 'MTR', type: 'MOTOR', area: 'FEED', description: 'Recreated' })
  s.enableDeviceLifecycle('MTR')
  assert.equal(s.loadDeviceConfiguration('MTR'), true)
  assert.equal(record().draft.confirmTimeSec, 6)
  assert.notEqual(m().confirmTimeSec, 6)
  assert.equal(m().downloaded, false)
  const before = JSON.stringify(record())
  for (const invalid of ['{', saved.replace('"MOTOR"', '"VALVE"'), saved.replace('"confirmTimeSec":6', '"confirmTimeSec":-1')]) {
    db.set(savedDeviceKey('MTR'), invalid)
    assert.equal(s.loadDeviceConfiguration('MTR'), false)
    assert.equal(JSON.stringify(record()), before)
  }
}))
test('locked workstation, insufficient rights and failed persistence cannot report Save/Download success', () => fixture(s => {
  prepare(s)
  const revision = record().savedRevision
  useSecurity.setState({ locked: true })
  assert.equal(s.saveDeviceConfiguration('MTR'), false)
  assert.equal(s.editDeviceDraft('MTR', { confirmTimeSec: 8 }), false)
  assert.equal(s.downloadDeviceConfiguration('MTR'), false)
  useSecurity.setState({ locked: false, currentUser: 'operator' })
  assert.equal(s.downloadDeviceConfiguration('MTR'), false)
  useSecurity.setState({ currentUser: 'admin' })
  global.window.localStorage.setItem = () => { throw new Error('Storage denied') }
  assert.equal(s.saveDeviceConfiguration('MTR'), false)
  assert.equal(record().savedRevision, revision)
  assert.equal(record().deployed, undefined)
}))
test('active command/feedback/applied channel prevents enable, replacement download and deletion', () => fixture(s => {
  s.startMotor('OTHER')
  assert.equal(s.enableDeviceLifecycle('OTHER'), false)
  prepare(s)
  s.setTraditionalInput('CTLR-IN', 1)
  s.tick(.1)
  assert.equal(s.downloadDeviceConfiguration('MTR'), false)
  s.setTraditionalInput('CTLR-IN', 0)
  s.tick(.1)
  assert.equal(s.downloadDeviceConfiguration('MTR'), true)
  s.tick(.1)
  s.startMotor('MTR')
  s.tick(.1)
  assert.equal(s.downloadDeviceConfiguration('MTR'), false)
  s.deleteModule('MTR')
  assert.ok(m())
}))
test('deletion/new project clears lifecycle; saved database remains explicit Load only', () => fixture((s, _, db) => {
  prepare(s)
  s.deleteModule('MTR')
  assert.equal(record(), undefined)
  assert.equal(m(), undefined)
  assert.ok(db.get(savedDeviceKey('MTR')))
  prepare(s, 'XV')
  s.newProject('blank')
  assert.deepEqual(useStore.getState().deviceLifecycle, {})
}))
