const assert = require('node:assert/strict')
const fs = require('node:fs')
const test = require('node:test')
const ts = require('typescript')
require.extensions['.ts'] = (module, filename) => {
  module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 }
  }).outputText, filename)
}
const { useStore } = require('../src/renderer/src/engine/store.ts')
const { useSecurity } = require('../src/renderer/src/engine/security.ts')
const { deviceEditorModules, parseDevice, savedDeviceKey } = require('../src/renderer/src/engine/deviceLifecycle.ts')
const { strategyModules } = require('../src/renderer/src/engine/motorStrategy.ts')
const { connectedModuleTags, buildControlDiagram } = require('../src/renderer/src/engine/controlDiagram.ts')
const { findDst } = require('../src/renderer/src/engine/traditionalIo.ts')
function fixture(run) {
  const before = { store: useStore.getState(), security: useSecurity.getState(), window: global.window }
  const alerts = [], db = new Map()
  global.window = { alert: message => alerts.push(message), localStorage: {
    setItem: (k, v) => db.set(k, v), getItem: k => db.get(k) ?? null
  } }
  try {
    useSecurity.setState({ currentUser: 'admin', locked: false })
    const s = useStore.getState()
    s.newProject('blank')
    useStore.setState({ running: true })
    for (const [tag, type] of [['XVSTAT-101', 'DI'], ['LI-101', 'AI']]) s.createModule({ tag, type, area: 'FEED', description: tag })
    s.createController('CTLR', 'Motor template')
    s.commissionController('CTLR')
    for (const [slot, type, dst] of [[3, 'DI', 'XI-2'], [4, 'DO', 'ZX-2'], [1, 'AI', 'LI-IN'], [2, 'DI', 'XV-IN']]) {
      s.addTraditionalCard('CTLR', slot, type)
      s.configureTraditionalChannel(`CTLR/C0${slot}`, 2, { dst, enabled: true })
    }
    s.bindAnalogDst('LI-101', 'input', 'LI-IN')
    s.bindDiscreteDst('XVSTAT-101', 'XV-IN')
    s.setTraditionalInput('LI-IN', 70)
    s.setTraditionalInput('XV-IN', 1)
    s.tick(.1)
    assert.equal(s.createMotorTemplate('MTR-102', 'FEED'), true)
    s.setFbInput('MTR-102/CND1', 'in1', { kind: 'ref', tag: 'XVSTAT-101', value: 0 })
    s.setFbInput('MTR-102/CND2', 'in1', { kind: 'ref', tag: 'LI-101', value: 0 })
    s.editDeviceDraft('MTR-102', { controllerTag: 'CTLR', inputDst: 'XI-2', outputDst: 'ZX-2' })
    run(s, alerts, db)
  } finally {
    useStore.setState(before.store, true)
    useSecurity.setState(before.security, true)
    if (before.window === undefined) delete global.window
    else global.window = before.window
  }
}
function motor() { return useStore.getState().modules['MTR-102'] }
function block(name) { return motor().ownedBlocks[name] }
function record() { return useStore.getState().deviceLifecycle['MTR-102'] }
function deploy(s) {
  assert.equal(s.saveDeviceConfiguration('MTR-102'), true)
  assert.equal(s.downloadDeviceConfiguration('MTR-102'), true)
  s.tick(.1)
}
test('template copy creates one owning motor, namespaced owned graph and inhibited offline draft, not independent live modules', () => fixture(s => {
  assert.equal(motor().templateId, 'MTR-11_ILOCK')
  assert.deepEqual(Object.keys(motor().ownedBlocks), ['CND1', 'CND2', 'BFI1', 'OR1', 'NOT1', 'AND1'])
  assert.equal(useStore.getState().modules['MTR-102/CND1'], undefined)
  s.tick(.1)
  assert.equal(block('CND1').bad, true)
  assert.equal(motor().downloaded, false)
  const view = deviceEditorModules(useStore.getState().modules, useStore.getState().deviceLifecycle)
  const connected = connectedModuleTags(view, 'MTR-102')
  for (const tag of ['MTR-102/CND1', 'MTR-102/CND2', 'MTR-102/BFI1', 'MTR-102/OR1', 'MTR-102/NOT1', 'MTR-102/AND1', 'XVSTAT-101', 'LI-101']) assert.ok(connected.includes(tag))
  const diagram = buildControlDiagram(connected, view)
  assert.ok(diagram.wires.some(w => w.fromTag === 'MTR-102/NOT1' && w.toTag === 'MTR-102' && w.which === 'ilk'))
  assert.ok(diagram.wires.some(w => w.fromTag === 'MTR-102/AND1' && w.toTag === 'MTR-102' && w.which === 'permissive'))
  assert.ok(diagram.wires.some(w => w.fromTag === 'MTR-102/CND1' && w.toTag === 'MTR-102/OR1'))
}))
test('saved owned configuration excludes live trap/timers; offline edits are isolated and Full deploy transfers together', () => fixture((s, _, db) => {
  s.setFbConfig('MTR-102/CND2', { expr: 'IN1 < 49', delaySec: 3 })
  assert.equal(record().draft.strategy.CND2.expr, 'IN1 < 49')
  assert.equal(block('CND2').expr, 'IN1 < 50')
  deploy(s)
  assert.equal(block('CND2').expr, 'IN1 < 49')
  assert.equal(block('CND2').delaySec, 3)
  const saved = parseDevice(db.get(savedDeviceKey('MTR-102')), 'MTR-102')
  assert.equal(saved.strategy.CND2.in1.tag, 'LI-101')
  assert.equal(saved.strategy.BFI1.firstOut, undefined)
  assert.equal(saved.strategy.CND2._timerElapsed, undefined)
  s.setDeviceOnline('MTR-102', false)
  s.setFbConfig('MTR-102/CND2', { delaySec: 9 })
  assert.equal(block('CND2').delaySec, 3)
  assert.equal(record().saved.strategy.CND2.delaySec, 3)
  assert.equal(record().deployed.strategy.CND2.delaySec, 3)
  s.loadDeviceConfiguration('MTR-102')
  assert.equal(record().draft.strategy.CND2.delaySec, 3)
}))
test('owned condition trips at exact4.0 boundary, traps cause2, de-energizes external DO and retains Reset Required lock', () => fixture(s => {
  deploy(s)
  s.setPermissive('MTR-102', true)
  s.startMotor('MTR-102')
  s.tick(.1)
  s.setTraditionalInput('XI-2', 1)
  s.tick(.1)
  assert.equal(motor().running, true)
  s.setTraditionalInput('LI-IN', 49)
  s.tick(3.9)
  assert.equal(block('CND2').out, 0)
  assert.equal(motor().interlock, false)
  s.tick(.1)
  assert.equal(block('CND2').out, 1)
  assert.equal(block('BFI1').firstOut, 2)
  assert.equal(findDst(useStore.getState().hardware, 'ZX-2').channel.value, 0)
  assert.equal(motor().running, true)
  assert.equal(motor().locked, true)
  s.setTraditionalInput('XI-2', 0)
  s.setTraditionalInput('LI-IN', 60)
  s.tick(.1)
  assert.equal(motor().running, false)
  assert.equal(motor().locked, true)
  s.resetDevice('MTR-102')
  s.tick(.1)
  assert.equal(motor().locked, false)
}))
test('owned online bypass routes actual OR indication; trap reset does not clear the active trip; Bad still fails safe', () => fixture(s => {
  deploy(s)
  s.setTraditionalInput('XV-IN', 0)
  s.tick(.1)
  assert.equal(block('BFI1').firstOut, 1)
  assert.equal(motor().interlock, true)
  assert.equal(s.setFbSafety('MTR-102/BFI1', 'RESET_IN', true), true)
  s.tick(.1)
  assert.equal(block('BFI1').firstOut, 0)
  assert.equal(motor().interlock, true)
  assert.equal(s.setFbSafety('MTR-102/CND1', 'BYPASS', true), true)
  s.tick(.1)
  assert.equal(block('CND1').out, 0)
  assert.equal(block('OR1').out, 1)
  assert.equal(motor().interlock, false)
  s.configureTraditionalChannel('CTLR/C02', 2, { dst: 'XV-IN', enabled: false })
  s.tick(.1)
  assert.equal(block('CND1').bad, true)
  assert.equal(block('BFI1').bad, true)
  assert.equal(motor().interlock, true)
}))
test('owned references validate atomically, online config rejects and blocks cannot be deleted independently', () => fixture((s, alerts) => {
  const before = JSON.stringify(record().draft.strategy)
  s.setFbInput('MTR-102/CND1', 'in1', { kind: 'ref', tag: 'MISSING', value: 0 })
  s.setFbConfig('MTR-102/CND2', { expr: 'IN1 <', delaySec: 4 })
  assert.equal(JSON.stringify(record().draft.strategy), before)
  deploy(s)
  s.setFbConfig('MTR-102/CND2', { delaySec: 6 })
  assert.equal(block('CND2').delaySec, 4)
  s.deleteModule('MTR-102/CND1')
  assert.ok(block('CND1'))
  assert.match(alerts.at(-1), /Owned template blocks/)
  s.deleteModule('MTR-102')
  assert.equal(motor(), undefined)
  assert.equal(useStore.getState().deviceLifecycle['MTR-102'], undefined)
}))
test('two template instances keep namespace/state/deployed configuration independent; duplicate copies reject', () => fixture(s => {
  assert.equal(s.createMotorTemplate('MTR-102', 'FEED'), false)
  assert.equal(s.createMotorTemplate('MTR-103', 'FEED'), true)
  deploy(s)
  s.setTraditionalInput('XV-IN', 0)
  s.tick(.1)
  assert.equal(block('BFI1').firstOut, 1)
  const other = useStore.getState().modules['MTR-103']
  assert.equal(other.ownedBlocks.BFI1.firstOut, undefined)
  assert.equal(other.ownedBlocks.BFI1.bad, true)
  assert.equal(useStore.getState().deviceLifecycle['MTR-103'].deployed, undefined)
  assert.equal(strategyModules(useStore.getState().modules)['MTR-103/CND1'].tag, 'MTR-103/CND1')
}))
test('exact p230 quoted source expressions persist/deploy and execute dependency-ordered course outcomes; source deletion fails safe with journal', () => fixture((s, _, db) => {
  s.setFbInput('MTR-102/CND1', 'in1', { kind: 'const', value: 0 })
  s.setFbInput('MTR-102/CND2', 'in1', { kind: 'const', value: 0 })
  s.setFbConfig('MTR-102/CND1', { expr: "'//XVSTAT-101/DI1/PV_D' = 0", delaySec: 0 })
  s.setFbConfig('MTR-102/CND2', { expr: "'//LI-101/AI1/PV' < 50", delaySec: 4 })
  deploy(s)
  assert.equal(block('CND2').bad, false)
  const saved = parseDevice(db.get(savedDeviceKey('MTR-102')), 'MTR-102')
  assert.equal(saved.strategy.CND2.expr, "'//LI-101/AI1/PV' < 50")
  const view = deviceEditorModules(useStore.getState().modules, useStore.getState().deviceLifecycle)
  const diagram = buildControlDiagram(connectedModuleTags(view, 'MTR-102'), view)
  assert.ok(diagram.wires.some(w => w.fromTag === 'LI-101' && w.toTag === 'MTR-102/CND2'))
  s.setTraditionalInput('LI-IN', 49)
  s.tick(3.9)
  assert.equal(block('CND2').out, 0)
  s.tick(.1)
  assert.equal(block('CND2').out, 1)
  assert.equal(block('BFI1').firstOut, 2)
  s.deleteModule('LI-101')
  s.tick(.1)
  assert.equal(block('CND2').bad, true)
  assert.equal(motor().interlock, true)
  assert.ok(useStore.getState().eventLog.some(e => e.tag === 'MTR-102/CND2' && /source Bad or unavailable/.test(e.description)))
}))
test('owned strategy is controller-bound; loss marks conditions/trip outputs Bad without losing captured history', () => fixture(s => {
  deploy(s)
  s.setTraditionalInput('XV-IN', 0)
  s.tick(.1)
  assert.equal(block('BFI1').firstOut, 1)
  const previousBlock = block('BFI1')
  s.failController('CTLR')
  s.tick(.1)
  assert.equal(block('BFI1').bad, true)
  assert.equal(block('BFI1').firstOut, 1)
  assert.equal(previousBlock.bad, false)
  assert.equal(motor().interlock, true)
  assert.equal(motor().ioInputBad, true)
  assert.equal(motor().ioOutputBad, true)
  assert.equal(s.setFbSafety('MTR-102/CND1', 'BYPASS', true), false)
}))
test('owned AND start permissive is independent of the NOT interlock; offline changes take effect only on saved Full deployment', () => fixture(s => {
  s.setFbInput('MTR-102/AND1', 'in1', { kind: 'const', value: 0 })
  deploy(s)
  assert.equal(block('NOT1').out, 1)
  assert.equal(motor().interlock, false)
  assert.equal(motor().permissiveOk, false)
  s.startMotor('MTR-102')
  s.tick(.1)
  assert.equal(findDst(useStore.getState().hardware, 'ZX-2').channel.value, 0)
  s.stopMotor('MTR-102')
  s.setDeviceOnline('MTR-102', false)
  s.setFbInput('MTR-102/AND1', 'in1', { kind: 'const', value: 1 })
  assert.equal(block('AND1').out, 0)
  deploy(s)
  assert.equal(motor().permissiveOk, true)
  assert.equal(motor().interlock, false)
  s.startMotor('MTR-102')
  s.tick(.1)
  assert.equal(findDst(useStore.getState().hardware, 'ZX-2').channel.value, 1)
}))
test('persistent owned configuration remains editable after loading into a recreated motor before first deployment', () => fixture(s => {
  s.saveDeviceConfiguration('MTR-102')
  s.newProject('blank')
  for (const [tag, type] of [['MTR-102', 'MOTOR'], ['XVSTAT-101', 'DI'], ['LI-101', 'AI']]) {
    s.createModule({ tag, type, area: 'FEED', description: 'Recreated' })
  }
  s.enableDeviceLifecycle('MTR-102')
  assert.equal(s.loadDeviceConfiguration('MTR-102'), true)
  s.setFbConfig('MTR-102/CND2', { delaySec: 8 })
  assert.equal(record().draft.strategy.CND2.delaySec, 8)
  assert.equal(record().saved.strategy.CND2.delaySec, 4)
  assert.equal(motor().ownedBlocks, undefined)
  assert.equal(s.saveDeviceConfiguration('MTR-102'), true)
  assert.equal(record().saved.strategy.CND2.delaySec, 8)
  assert.equal(motor().downloaded, false)
}))
test('renaming the plant area carries the entire owned graph without aliasing the deployed prior scan', () => fixture(s => {
  deploy(s)
  const previous = block('CND1')
  assert.equal(s.renameArea('FEED', 'PLANT_AREA_A'), true)
  assert.equal(motor().area, 'PLANT_AREA_A')
  assert.equal(block('CND1').area, 'PLANT_AREA_A')
  assert.equal(block('AND1').area, 'PLANT_AREA_A')
  assert.equal(previous.area, 'FEED')
  s.setDeviceOnline('MTR-102', false)
  const view = deviceEditorModules(useStore.getState().modules, useStore.getState().deviceLifecycle)
  assert.equal(view['MTR-102/CND2'].area, 'PLANT_AREA_A')
}))
